<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\AddToWishlist $block */
?>
<div class="custom-title-changer">
<span class="custom-span-title">Daily Deals</span>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)
                ->jsonEncode($block->getWishlistOptions());
            ?>
        }
    }
</script>
